[package]
name = "podmanrs"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
varlink = "5.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
failure_derive = "0.1"
failure = "0.1"

[build-dependencies]
varlink_generator = "6"
